arena/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='index'),
    url(r'^new/$', views.NewView.as_view(), name='new'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^accounts/', include('allauth.urls'), name='login'),
    url(r'^settings/$', views.SettingsView.as_view(), name='settings'),
    url(r'^@(?P<username>\w+)$', views.UserView.as_view(), name='user_profile'),
    url(r'^(?P<fighter_slug>\w+)/$', views.FighterView.as_view(), name='fighter_profile'),
    url(r'^(?P<fighter_slug>\w+)/edit/$', views.FighterView.as_view(), name='fighter_edit'),
    url(r'^(?P<slug_one>\w+)/(?P<slug_two>\w+)/$', views.BattleView.as_view(), name='battle_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arena/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse



class BaseModel(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Fighter(BaseModel):
    creator = models.ForeignKey('auth.User', related_name='fighters')
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='uploads')

    def __str__(self):
        return self.slug

    @property
    def battles(self):
        sql = models.Q(fighter_one=self) | models.Q(fighter_two=self)
        return Battle.objects.filter(sql)


class Battle(BaseModel):
    creator = models.ForeignKey('auth.User', related_name='battles')
    fighter_one = models.ForeignKey(Fighter, related_name='+')
    fighter_two = models.ForeignKey(Fighter, related_name='+')

    def __str__(self):
        return str(self.id)

    @property
    def fighters(self):
        return Fighter.objects.filter(id__in=[self.fighter_one_id, self.fighter_two_id])

    def get_absolute_url(self):
        return reverse('battle_page', args=(self.fighter_one.slug, self.fighter_two.slug))

    class Meta:
         unique_together = ('fighter_one', 'fighter_two')


class Vote(BaseModel):
    creator = models.ForeignKey('auth.User', related_name='votes')
    battle = models.ForeignKey(Battle, null=False, blank=False)
    fighter = models.ForeignKey(Fighter, null=False, blank=False)

    class Meta:
         unique_together = ('battle', 'creator')


class Comment(BaseModel):
    creator = models.ForeignKey('auth.User', related_name='comments')
    battle = models.ForeignKey(Battle, null=False, blank=False)
    fighter = models.ForeignKey(Fighter, null=False, blank=False)
    description = models.TextField()

arena/forms.py
import itertools

from arena.models import Battle, Vote, Fighter, Comment

from django import forms
from django.utils.text import slugify


class FighterForm(forms.ModelForm):
    slug = forms.CharField(required=False)

    def save(self):
        instance = super(FighterForm, self).save(commit=False)
        instance.slug = orig = slugify(instance.name)
        for x in itertools.count(1):
            if not Fighter.objects.filter(slug=instance.slug).exists():
                break
            instance.slug = '%s_%d' % (orig, x)
        instance.save()
        return instance

    class Meta:
        model = Fighter
        fields = ('name', 'description', 'image', 'slug')


class BattleForm(forms.ModelForm):

    def exists(self):
        fighter_one = Fighter.objects.get(id=self.data['fighter_one'])
        fighter_two = Fighter.objects.get(id=self.data['fighter_two'])
        sql = Battle.objects.filter(fighter_one=fighter_one, fighter_two=fighter_two) | Battle.objects.filter(fighter_one=fighter_two, fighter_two=fighter_one)
        if sql.count() == 0:
            return False
        else:
            return True

    def save(self):
        instance = super(BattleForm, self).save(commit=False)
        instance.save()
        return instance

    class Meta:
        model = Battle
        fields = ('fighter_one', 'fighter_two', 'creator')


class VoteForm(forms.ModelForm):

    class Meta:
        model = Vote
        fields = ('fighter', 'battle')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('battle', 'fighter', 'description')

arena/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template import RequestContext
from django.views.generic import View
from django import forms

from .models import Battle, Fighter, Comment, Vote
from .forms import BattleForm, VoteForm, FighterForm, CommentForm


class NewView(LoginRequiredMixin, View):
    login_url = 'facebook_login'
    redirect_field_name = '/new/'

    def post(self, request):
        fighters = []
        forms = []
        for prefix in ('one', 'two'):
            form = FighterForm(request.POST, request.FILES, prefix=prefix)
            if form.data[prefix + '-slug'] == '':
                form.instance.creator = request.user
                form.save()
                fighter = form.instance
            else:
                fighter = Fighter.objects.get(slug=request.POST[prefix + '-slug'])
            fighters.append(fighter)
            forms.append(form)

        data = {}
        data['fighter_one'] = fighters[0].id
        data['fighter_two'] = fighters[1].id
        data['creator'] = request.user.id

        battle = BattleForm(data)

        if battle.exists():
            return self.get(request, forms=forms)
        else:
            battle.save()
            return redirect(battle.instance)

    def get(self, request, success=None, forms=None):
        if forms:
            form1 = forms[0]
            form2 = forms[1]
        else:
            form1 = FighterForm(prefix='one')
            form2 = FighterForm(prefix='two')
        #FIXME
        #form1.fields['slug'].widget = forms.HiddenInput()
        #form2.fields['slug'].widget = forms.HiddenInput()
        return render(request, 'new.html', {'fighter1': form1,
                                            'fighter2': form2,
                                            'success': success})

class BattleView(View):
    def get(self, request, slug_one, slug_two):
        try:
            fighter_one = Fighter.objects.get(slug=slug_one)
            fighter_two = Fighter.objects.get(slug=slug_two)
        except Fighter.DoesNotExist:
            return HttpResponse("Fighter doesn't exist")

        battle = Battle.objects.filter(fighter_one=fighter_one, fighter_two=fighter_two) | Battle.objects.filter(fighter_one=fighter_two, fighter_two=fighter_one)

        if battle.count() == 0:
            return HttpResponse("Battle doesn't exist")

        latest_comment_fighter_one = Comment.objects.filter(fighter=battle[0].fighter_one)[:5]
        latest_comment_fighter_two = Comment.objects.filter(fighter=battle[0].fighter_two)[:5]

        return render(request, 'battle.html', { 'battle': battle[0],
                                                'latest_comment_fighter_one': latest_comment_fighter_one,
                                                'latest_comment_fighter_two':latest_comment_fighter_two,})

    def post(self, request, slug_one, slug_two):
        if request.POST['action'] == "vote":
            # Check if battle exists
            fighter_one = Fighter.objects.get(slug=slug_one)
            fighter_two = Fighter.objects.get(slug=slug_two)
            battle = Battle.objects.filter(fighter_one=fighter_one, fighter_two=fighter_two) | Battle.objects.filter(fighter_one=fighter_two, fighter_two=fighter_one)
            vote = Vote.objects.filter(creator=request.user, battle=battle)
            if vote.count() != 0:
                return HttpResponse("Already voted in this battle")
            # Save vote
            form = VoteForm(request.POST)
            form.instance.creator = request.user
            form.save()
        if request.POST['action'] == "comment":
            form = CommentForm(request.POST)
            form.instance.creator = request.user
            form.save()
        return self.get(request, slug_one, slug_two)

class HomeView(View):
    def get(self, request):
        battles = Battle.objects.filter()[:20]

        return render(request, 'index.html', {'battles': battles,})


class FighterView(View):
    def get(self, request, fighter_slug):
        fighter = get_object_or_404(Fighter, slug=fighter_slug)
        battles = Battle.objects.filter(fighter_one=fighter) | Battle.objects.filter(fighter_two=fighter)

        return render(request, 'fighter_profile.html', {'battles': battles,})


class UserView(View):
    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        latest_battles = Battle.objects.filter(creator=user)
        latest_fighters = Fighter.objects.filter(creator=user)
        latest_comments = Comment.objects.filter(creator=user)
        latest_votes = Vote.objects.filter(creator=user)

        return render(request, 'user_profile.html', {'username':username, 'latest_battles':latest_battles, 'latest_fighters':latest_fighters, 'latest_comments':latest_comments, 'latest_votes':latest_votes,})


class SettingsView(View):
    def get(self, request):
        return HttpResponse("Settings page")

arena/templates/battle.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{{battle.fighter_one.name}} vs {{battle.fighter_two.name}}</title>
		<!-- Description, Keywords and Author -->
		<meta name="description" content="Your description">
		<meta name="keywords" content="Your,Keywords">
		<meta name="author" content="ResponsiveWebInc">

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- Styles -->
		<!-- Bootstrap CSS -->
        {% load static from staticfiles %}
		<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
		<!-- Font awesome CSS -->
		<link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">


		<!-- Main CSS -->
		<link href="{% static "css/estilos.css" %}" rel="stylesheet">

		<!-- Favicon -->
		<link rel="shortcut icon" href="#">
	</head>

	<body>
		<!-- UI X -->
		<div class="ui-97">
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-sm-4">
						<!-- UI Member -->
						<div class="ui-member">
                            <div class="ui-310">
			                    <div class="container-fluid">
				                    <!-- Item -->
				                    <div class="ui-item clearfix">
					                    <!-- Heading -->
					                    <h3 class="bg-red"><a href="#">Bandwidth</a></h3>
					                    <!-- Content -->
					                    <div class="ui-content">
						                    <!-- Heading -->
						                    <h4 class="bg-red"  data-valuemax="20" ><span></span></h4>
					                    </div>
				                    </div>
                                </div>
                            </div>
							<!-- UIs member header -->
							<div class="ui-head">
								<!-- Member background image -->
								<img class="ui-back img-responsive" src="{{battle.fighter_one.image.url}}" alt="" />
							</div>
							<!--Name / Heading -->
							<h3><a href="#">{{battle.fighter_one}}</a></h3>
							<!-- Member designation -->
							<span>
                                <form action="{% url 'battle_page' slug_one=battle.fighter_one.slug slug_two=battle.fighter_two.slug %}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}{{battle.fighter_one.vote_set.count}}
                                    <input name="battle" type="hidden" value="{{ battle.id }}">
                                    <input type="hidden" name="action" value="vote" />
                                    <button name="fighter" type="submit" value="{{battle.fighter_one.id}}">Vote</button>
                                </form>
                            </span>
							<!-- Social media links -->
							<div class="social">
								<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
								<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
								<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
								<a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a>
							</div>
                            <!-- Description -->
                            <div>
                                {{battle.fighter_one.description}}
                            </div>
                            <!-- Comment -->
                            <hr />
                            <ul>
                            {% for comment in latest_comment_fighter_one %}
                                <li>{{ comment.creator }}: {{ comment.description }} ({{ comment.date_updated }})</li>
                            {% endfor %}
                            </ul>
                            <form action="{% url 'battle_page'  slug_one=battle.fighter_one.slug slug_two=battle.fighter_two.slug %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input name="battle" type="hidden" value="{{ battle.id }}">
                                <input type="hidden" name="action" value="comment" />
                                <input name="fighter" type="hidden" value="{{battle.fighter_one.id}}">
                                <input name="description" type="text">
                                <button type="submit">Comment</button>
                            </form>
						</div>
					</div>
                    <div class="col-md-4 col-sm-4">
                        <img class="ui-img img-responsive" src="/media/vs.png" alt="" />
                    </div>
					<div class="col-md-4 col-sm-4">
						<!-- UI Member -->
						<div class="ui-member">
                            <div class="ui-310">
			                    <div class="container-fluid">
				                    <!-- Item -->
				                    <div class="ui-item clearfix">
					                    <!-- Heading -->
					                    <h3 class="bg-red"><a href="#">Bandwidth</a></h3>
					                    <!-- Content -->
					                    <div class="ui-content">
						                    <!-- Heading -->
						                    <h4 class="bg-red"  data-valuemax="20" ><span></span></h4>
					                    </div>
				                    </div>
                                </div>
                            </div>
							<!-- UIs member header -->
							<div class="ui-head">
								<!-- Member background image -->
								<img class="ui-back img-responsive" src="{{battle.fighter_two.image.url}}" alt="" />
							</div>
							<!--Name / Heading -->
							<h3><a href="#">{{battle.fighter_two}}</a></h3>
							<!-- Member designation -->
							<span>
                                <form action="{% url 'battle_page'  slug_one=battle.fighter_one.slug slug_two=battle.fighter_two.slug %}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}{{battle.fighter_two.vote_set.count}}
                                    <input name="battle" type="hidden" value="{{ battle.id }}">
                                    <input type="hidden" name="action" value="vote" />
                                    <button name="fighter" type="submit" value="{{battle.fighter_two.id}}">Vote</button>
                                </form>
                            </span>
							<!-- Social media links -->
							<div class="social">
								<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
								<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
								<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
								<a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a>
							</div>
                            <!-- Description -->
                            <div>
                                {{battle.fighter_two.description}}
                            </div>
                            <!-- Comment -->
                            <hr />
                            <ul>
                            {% for comment in latest_comment_fighter_two %}
                                <li>{{ comment.creator }}: {{ comment.description }} ({{ comment.date_updated }})</li>
                            {% endfor %}
                            </ul>
                            <form action="{% url 'battle_page'  slug_one=battle.fighter_one.slug slug_two=battle.fighter_two.slug %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input name="battle" type="hidden" value="{{ battle.id }}">
                                <input type="hidden" name="action" value="comment" />
                                <input name="fighter" type="hidden" value="{{battle.fighter_two.id}}">
                                <input name="description" type="text">
                                <button type="submit">Comment</button>
                            </form>
						</div>
					</div>
				</div>
			</div>

		</div>

		<!-- Javascript files -->
		<!-- jQuery -->
		<script src="{% static "js/jquery.js" %}"></script>
		<!-- Bootstrap JS -->
		<script src="{% static "js/bootstrap.min.js" %}"></script>
		<!-- Placeholder JS -->
		<script src="{% static "js/placeholder.js" %}"></script>
		<!-- Respond JS for IE8 -->
		<script src="{% static "js/respond.min.js" %}"></script>
		<!-- HTML5 Support for IE -->
		<script src="{% static "js/html5shiv.js" %}"></script>
		<script>
		<!-- Animation -->
		$(document).ready(function(){
			<!-- For Each Heading -->
			$(".ui-content h4").each(function(){
				var max = $(this).attr("data-valuemax");
				$(this).prop('Counter', 0 ).animate({ width: max + "%", Counter: max }, {			//Min value 0 and Max value attribute value
					duration: 2000,
					easing: 'swing',
					step: function () {
					  $(this).children("span").text(Math.ceil(this.Counter) + "%");		//Count Number
					}
				});
			});
		});
		</script>
	</body>
</html>

arena/templates/battle_new.html
{% if request.user.is_authenticated %}
    Create New Battle<br />

    <form action="{% url 'new' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form.as_p }}</p>
        <p><input type="submit" value="New Battle" /></p>
    </form>

    Or
    </br></br>
    Create New Fighter

    <form action="{% url 'new' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form2.as_p }}</p>
        <p><input type="submit" value="New Fighter" /></p>
    </form>
{% else %}
    <a href="{% url 'account_login' %}">Login</a>
{% endif %}

arena/templates/fighter_profile.html
Fighter profile page<br />

{% for battle in battles %}
    <li>{{ battle.id }}: {{ battle.fighter_one }} vs {{ battle.fighter_two }}</li>
{% endfor %}

arena/templates/index.html
Index Page<br />

{% if request.user.is_authenticated %}
    Username: {{ request.user.username }}
    <br />
    <a href="{% url 'settings' %}">Settings</a></br>
    <a href="{% url 'account_logout' %}">Logout</a>
{% else %}
    {% load socialaccount %}
    <a href="{% provider_login_url "facebook" method="oauth2" next="/" %}">Login</a>
{% endif %}

<br />

{% for battle in battles %}
    {{ battle.id }}: {{ battle.fighter_one }} vs {{ battle.fighter_two }} <a href="{% url 'battle_page' battle.fighter_one battle.fighter_two %}">[Link]</a><br />
{% endfor %}

arena/templates/new.html
{% if request.user.is_authenticated %}

{% if error %}
    <h1 style="color: red;">{{ error }}</h1>
{% endif %}

<form action="{% url 'new' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset>
        <legend>Figther 1</legend>
        {{ fighter1.as_p }}
    </fieldset>

    <fieldset>
        <legend>Figther 2</legend>
        {{ fighter2.as_p }}
    </fieldset>

    <p>&nbsp;</p>
    <input type="submit" value="Create battle" />
</form>

{% else %}
    {% load socialaccount %}
    <a href="{% provider_login_url "facebook" method="oauth2" next="/new/" %}">Login</a>
{% endif %}

arena/templates/new_comment.html
You commented on: {{ fighter.name }}

arena/templates/new_fighter.html
You voted for: {{ fighter.name }}

<form action="{% url 'new_fighter' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.as_p }}</p>
    <p><input type="submit" value="New Fighter" /></p>
</form>

arena/templates/user_profile.html
{{ username }} profile page<br />

Battles.id:
{% for battle in latest_battles %}
    {{ battle.id }}<br />
{% endfor %}

<br />

Fighters:
{% for fighter in latest_fighters %}
    {{ fighter.name }}<br />
{% endfor %}

<br />

Comments:
{% for comment in latest_comments %}
    {{ comment.fighter }}: {{ comment.description }}<br />
{% endfor %}

<br />

Votes:
{% for vote in latest_votes %}
    {{ vote.battle.id }} - {{ vote.fighter.name }}<br />
{% endfor %}

arena/templates/vote_edit.html
Edit Vote page<br />

<form action="{% url 'vote' %}" method="PUT" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.as_p }}</p>
    <p><input type="submit" value="Edit Vote" /></p>
</form>

arena/templates/vote_new.html
New Vote page<br />

<form action="{% url 'vote' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.as_p }}</p>
    <p><input type="submit" value="New Vote" /></p>
</form>